import { useMemo, useState } from 'react';
type Entry = { id: string; title: string; href: string; kind: string; category: string; readingMinutes: number; cost?: { low: number; high: number; unit: string }; contexts?: string[] };
export default function ArticleCollection({ entries, resource }: { entries: Entry[]; resource: string }) {
  const [query, setQuery] = useState(''), [category, setCategory] = useState(''), [context, setContext] = useState('');
  const categories = [...new Set(entries.map(entry => entry.category))];
  const contexts = [...new Set(entries.flatMap(entry => entry.contexts || []))];
  const visible = useMemo(() => entries.filter(entry => (!category || entry.category === category) && (!context || entry.contexts?.includes(context)) && query.toLowerCase().split(/\s+/).every(word => `${entry.id} ${entry.title} ${entry.category}`.toLowerCase().includes(word))), [query, category, context, entries]);
  return <section className="rc-collection" aria-label="Resource contents"><div className="rc-collection-tools"><label>Find {resource === 'catalog' ? 'an incentive' : 'a topic'}<input type="search" placeholder={resource === 'communications' ? 'Search titles or message IDs' : 'Search titles'} value={query} onChange={event => setQuery(event.target.value)} /></label>{categories.length > 1 && <label>Category<select value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{categories.map(value => <option key={value}>{value}</option>)}</select></label>}{contexts.length > 0 && <label>Organization<select value={context} onChange={event => setContext(event.target.value)}><option value="">All organizations</option>{contexts.map(value => <option key={value}>{value}</option>)}</select></label>}</div><p className="rc-result-count" role="status">{visible.length} {resource === 'catalog' ? 'ideas' : 'topics'}</p><div className="rc-article-list">{visible.map(entry => <a key={entry.id} href={entry.href}><div><span className="rc-item-kind">{entry.kind === 'template' ? `${entry.id} · Template` : entry.category}</span><strong>{entry.title}</strong></div><span className="rc-item-end">{entry.cost ? `$${entry.cost.low}–$${entry.cost.high}` : `${entry.readingMinutes} min read`}<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m9 5 7 7-7 7" /></svg></span></a>)}</div>{!visible.length && <div className="rc-empty"><h3>No matching topics</h3><p>Try a shorter search or clear the filters.</p><button type="button" className="rc-button rc-button-secondary" onClick={() => { setQuery(''); setCategory(''); setContext(''); }}>Clear filters</button></div>}</section>;
}
