import { useEffect, useState } from 'react';
type Stage = { id: string; title: string; goal: string; outcomes: string[]; links: { kind: string; id: string; label: string; href: string }[] };
const key = 'xp-resource-center-preparation-v1';
const formats: Record<string, string> = { guide: 'PDF', catalog: 'XLSX', builder: 'XLSX', communications: 'DOCX', rules: 'DOCX', kickoff: 'PPTX' };
const stageHref = (link: Stage['links'][number]) => link.kind === 'download' ? `/resources/ambassador-toolkit/downloads/${link.id}` : `/resources/ambassador-toolkit/${link.kind === 'message' ? 'communications' : link.kind}/${link.id}`;
export default function LaunchChecklist({ stages }: { stages: Stage[] }) {
  const [checked, setChecked] = useState<Record<string, boolean>>({}), [status, setStatus] = useState('');
  useEffect(() => { try { const value = JSON.parse(sessionStorage.getItem(key) || '{}'); const valid: Record<string, boolean> = {}; stages.forEach(stage => stage.outcomes.forEach((_, i) => { valid[`${stage.id}/${i}`] = value[`${stage.id}/${i}`] === true; })); setChecked(valid); } catch { setStatus('Progress cannot be saved in this browser. You can still use the checklist.'); } }, []);
  const complete = stages.filter(stage => stage.outcomes.every((_, i) => checked[`${stage.id}/${i}`])).length;
  function update(id: string, value: boolean) { const next = { ...checked, [id]: value }; setChecked(next); try { sessionStorage.setItem(key, JSON.stringify(next)); setStatus('Preparation progress saved for this browser session.'); } catch { setStatus('Progress cannot be saved in this browser.'); } }
  return <details className="rc-launch-checklist"><summary><span>Follow a launch checklist</span><small>{complete} of {stages.length} preparation stages complete</small></summary><p className="rc-muted">Your organization makes and reviews these decisions. This checklist tracks preparation; it does not approve the program or measure ambassador activity.</p><div className="rc-launch-stages">{stages.map((stage, index) => <details key={stage.id}><summary><span>{index + 1}</span><strong>{stage.title}</strong>{stage.outcomes.every((_, i) => checked[`${stage.id}/${i}`]) && <small>Complete</small>}</summary><p>{stage.goal}</p>{stage.outcomes.map((outcome, i) => <label className="rc-check" key={i}><input type="checkbox" checked={checked[`${stage.id}/${i}`] || false} onChange={event => update(`${stage.id}/${i}`, event.target.checked)} />{outcome}</label>)}<nav aria-label={`${stage.title} resources`}>{stage.links.map(link => <a key={`${link.kind}/${link.id}`} href={stageHref(link)}>{link.label}{link.kind === 'download' ? ` (${formats[link.id]})` : ''}</a>)}</nav></details>)}</div><p className="rc-muted" role="status">{status}</p></details>;
}
